development:
  clients:
    default:
      database: mysms_messenger_api_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: mysms_messenger_api_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
